### ISSUE TITLE
Error in iw_parse.py

### ISSUE THREAD

**Issue by adw4re** [s0lst1c3/eaphammer#99] opened 2019-07-26 06:46 UTC
./eaphammer --pmkid --interface wlan0 --essid example

```
Traceback (most recent call last):
  File "./eaphammer", line 635, in <module>
    pmkid_attack()
  File "./eaphammer", line 344, in pmkid_attack
    networks = iw_parse.iw_parse.get_interfaces(interface=str(interface))
  File "/root/eaphammer/core/iw_parse/iw_parse.py", line 284, in get_interfaces
    return get_parsed_cells(call_iwlist(interface).split('\n'))
TypeError: a bytes-like object is required, not 'str'

```

**Comment by shinhub** [comment] 2019-07-28 09:28
Please see #75

**Comment by s0lst1c3** [comment] 2019-07-28 22:19
@adw4re  Thanks for pointing this out. Closing since it's a duplicate of #75.

**Closed by s0lst1c3** 2019-07-28 22:19 UTC

**Comment by Guidonz95** [comment] 2025-01-11 10:41
@adw4re do you maybe happen to be the same Adw4re from the XperiFix?
