### ISSUE TITLE
Hostile-portal: a bytes-like object is required, not 'int'

### ISSUE THREAD

**Issue by KevinCarroll7737** [s0lst1c3/eaphammer#74] opened 2019-05-14 04:45 UTC
Had the same issue running --hostile-portal on both Ubuntu16.04 and Kali 4.19.x

EDIT: eaphammer version: v0.7.0

# uname -a
Linux srb 4.15.0-48-generic #51~16.04.1-Ubuntu SMP Fri Apr 5 12:01:12 UTC 2019 x86_64 GNU/Linux

# pip --version
/home/oem/.local/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
pip 19.1.1 from /home/oem/.local/lib/python3.5/site-packages/pip (python 3.5)

# python --version
Python 2.7.12

# python3 --version
Python 3.5.2

# gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ./eaphammer --interface wlx00c0caa84aa3 --essid TotallyLegit --hw-mode n --channel 36 --auth open --hostile-portal

--------------
Exception happened during processing of request from ('192.168.1.2', 5353)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/oem/git/tools/_wifi/eaphammer/core/poisoners/MDNS.py", line 47, in handle
    Request_Name = Parse_MDNS_Name(data)
  File "/home/oem/git/tools/_wifi/eaphammer/core/poisoners/MDNS.py", line 27, in Parse_MDNS_Name
    NameLen = struct.unpack('>B',data[0])[0]
TypeError: a bytes-like object is required, not 'int'
----------------------------------------

**Comment by xkill** [comment] 2019-06-05 10:41
Same problem here, when a client connects to the network:

```
Exception happened during processing of request from ('10.0.0.175', 5353)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/src/eaphammer/core/poisoners/MDNS.py", line 47, in handle
    Request_Name = Parse_MDNS_Name(data)
  File "/usr/local/src/eaphammer/core/poisoners/MDNS.py", line 27, in Parse_MDNS_Name
    NameLen = struct.unpack('>B',data[0])[0]
TypeError: a bytes-like object is required, not 'int'
```

**Comment by s0lst1c3** [comment] 2019-06-13 19:11
Thanks for reporting this. Most likely this is a type issue caused by our
migration to Python 3 (see:
https://twitter.com/s0lst1c3/status/1093740080366182401). Really appreciate
the bug report, I'll get this fixed in the next few days.

**Comment by mlinton** [comment] 2019-06-24 21:47
Hey @s0lst1c3 thanks again for the hard work put into this.  Just wondering if you had a chance to dig into the fix for this.  We're just in a process of trying it out for an EAP spraying session and maybe we can help you fix/test this.

Cheers.

**Comment by s0lst1c3** [comment] 2019-06-25 08:34
@mlinton

Long story short, this has really snowballed. The Hostile Portal functionality relies on Responder. I’ve been slowly plodding my way through getting Responder’s LLMNR poisoner to work again, but there are a lot of subtle bytes / Unicode issues that are rearing their ugly heads. I’m going to reach out to @skelsec, who has been actively working on a Python 3 port for well over a year. Skelsec’s code appears to be in beta 
, but if enough of it is working I’d like to see if we can rely on it instead of vanilla Responder. No sense reinventing the wheel if someone else has a working solution to this problem. I’ll keep you all updated.

**Comment by s0lst1c3** [comment] 2019-06-25 08:36
P.S. - the related PMKID issue should be an easier fix since there’s a lot less Python 3 code to worry about (it just calls a tool written in C).

**Closed** 2019-06-26 08:38 UTC
