### ISSUE TITLE
hostapd build failing in Kali/Parrot

### ISSUE THREAD

**Issue by cblopez** [s0lst1c3/eaphammer#222] opened 2024-09-19 07:04 UTC
The `hostapd` package is not working on the latest Kali Linux and ParrotOS versions when being compiled during the `kali-setup` or `parrot-setup` scripts.

**Environment**

- Platform: VMWare Workstation PRO 17.5.1 build-23298084
- Operating system: Kali Linux
```
─# uname -a                               
Linux kali 6.10.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.10.9-1kali1 (2024-09-09) x86_64 GNU/Linux
```

**Steps to reproduce**

1) Run `sudo apt update -y && apt upgrade -y`
2) Clone the repository and execute `./kali-setup`
3) Inspect the output from the script and find the following issue in the `hostapd` section:
```
[*] Compiling hostapd...

config_file.c: In function ‘hostapd_config_read_maclist’:
config_file.c:322:30: error: assignment to ‘char’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
  322 |                 addr_str[18] = ""; // 18 == length of ascii mac representation + null terminator
      |                              ^
config_file.c:323:30: error: assignment to ‘char’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
  323 |                 mask_str[18] = "ff:ff:ff:ff:ff:ff"; // 18 == length of ascii mac representation + null terminator
      |                              ^
config_file.c:385:60: warning: operation on ‘i’ may be undefined [-Wsequence-point]
  385 |                 for (i = 0; i < ETH_ALEN; addr[i] &= mask[i++]);
      |                                                           ~^~
config_file.c:385:60: warning: operation on ‘i’ may be undefined [-Wsequence-point]
make: *** [Makefile:1301: config_file.o] Error 1
```

****

**Expected behavior**

After installing, `eaphammer` should work correctly but is now raising an error due to the missing `libhostapd-eaphammer.so`, which was not compiled correctly

**Screenshots**

![image](https://github.com/user-attachments/assets/8778bb1f-0bf7-4376-a07b-476f7615abbc)

![image](https://github.com/user-attachments/assets/a0d6ef56-dace-49b1-8a33-15b3a8596049)

**Comment by s0lst1c3** [comment] 2024-09-22 22:31
Duplicate of #218

**Closed by s0lst1c3** 2024-09-22 22:31 UTC
